lzc-sdk-version: "0.1"
application:
  subdomain: frames
  background_task: true
  multi_instance: false
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://frames:3000/
services:
  frames:
    # upstream: elevenam/frames:2025-04-01-12-49@sha256:d2dde37bc48594d7d5b627899c2ca626f529d1c8b6fe26a7e3240765b016fbdc
    image: registry.lazycat.cloud/czyt/elevenam/frames:49096a55ecfa4dca
    environment:
      - DATABASE_URL=postgres://frames:{{ stable_secret "db_password" }}@postgres:5432/frames
      - DIRECT_DATABASE_URL=postgres://frames:{{ stable_secret "db_password" }}@postgres:5432/frames
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TTL=86400
      - REDIS_DB=0
      - JWT_SECRET={{ stable_secret "jwt_secret" }}
    depends_on:
      - postgres
      - redis
    binds:
      - /lzcapp/var/media:/media
  postgres:
    # upstream: pgvector/pgvector:0.8.6-pg14
    image: registry.lazycat.cloud/czyt/pgvector/pgvector:fd69e5f3504b9387
    environment:
      - POSTGRES_USER=frames
      - POSTGRES_PASSWORD={{ stable_secret "db_password" }}
      - POSTGRES_DB=frames
    binds:
      - /lzcapp/var/data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U frames
      start_period: 60s
  redis:
    # upstream: library/redis:7.4-alpine
    image: registry.lazycat.cloud/czyt/library/redis:feb21bfd39585516
    binds:
      - /lzcapp/var/data:/data
