lzc-sdk-version: "0.1"
name: Frames
package: cloud.lazycat.app.frames
version: 0.0.1
description: 您的现代流媒体服务平台
homepage: https://github.com/Eleven-am/frames
author: Eleven-am
application:
  subdomain: frames
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://frames:3000/
services:
  frames:
    image: docker.hlmirror.com/elevenam/frames:latest
    environment:
      - DATABASE_URL=postgres://frames:frames_password@postgres:5432/frames
      - DIRECT_DATABASE_URL=postgres://frames:frames_password@postgres:5432/frames
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TTL=86400
      - REDIS_DB=0
      - JWT_SECRET=lazycat#frames
    depends_on:
      - postgres
      - redis
    binds:
      - /lzcapp/var/media:/media

  postgres:
    image: docker.hlmirror.com/pgvector/pgvector:pg14
    environment:
      - POSTGRES_USER=frames
      - POSTGRES_PASSWORD=frames_password
      - POSTGRES_DB=frames
    binds:
      - /lzcapp/var/data:/var/lib/postgresql/data
    health_check:
       test:
        - CMD-SHELL
        - pg_isready -U frames
       start_period: 60s      
      
  redis:
    image: docker.hlmirror.com/redis:alpine
    binds:
      - /lzcapp/var/data:/data
